// apps/my-fancy-app/src/islands/counter-vue/Counter.vue
<script setup>
import { ref } from 'vue';
import { counter as sharedCounter } from '../../counter-shared/counter.js';

const count = ref(0);

function increment() {
	count.value++;
	sharedCounter.count.value++;
}

function decrement() {
	count.value--;
	sharedCounter.count.value--;
}
</script>

<template>
	<h2>Vue count: {{ count }}</h2>
	<h3>Shared count: {{ sharedCounter.count }}</h3>
	<button @click="increment">+</button>
	<button @click="decrement">-</button>
</template>

// apps/my-fancy-app/src/islands/counter-svelte/Counter.svelte
<script>
	import { counter as sharedCounter } from '../../counter-shared/counter.js';

	let count = $state(0);
	let sharedCount = $state(0);

	function increment() {
		count += 1;
		sharedCounter.increment();
	}

	function decrement() {
		count -= 1;
		sharedCounter.decrement();
	}

	sharedCounter.subscribe((value) => {
		sharedCount = value;
	});
</script>

<h2>Svelte count: {count}</h2>
<h3>Shared count: {sharedCount}</h3>
<button onclick={increment}>+</button>
<button onclick={decrement}>-</button>
